export const LaundryTheme = {
  colors: {
    primary: "#4C107D",
    primaryDark: "#3A096C",
    primarySoft: "#F0E8FF",
    accent: "#8B5CF6",
    ink: "#1D0B36",
    muted: "#756593",
    card: "#FFFFFF",
    border: "#E6DCFA",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    bgStart: "#F3EBFB",
    bgEnd: "#EBE3F7",
  },
  typography: {
    display: {
      fontSize: 36,
      lineHeight: 42,
      letterSpacing: -0.6,
      fontWeight: "800" as const,
    },
    heading: {
      fontSize: 24,
      lineHeight: 30,
      letterSpacing: -0.4,
      fontWeight: "800" as const,
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
      letterSpacing: 0,
      fontWeight: "400" as const,
    },
    label: {
      fontSize: 11,
      lineHeight: 14,
      letterSpacing: 1.4,
      fontWeight: "800" as const,
      textTransform: "uppercase" as const,
    },
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 22,
    xl: 30,
  },
  radius: {
    sm: 10,
    md: 16,
    lg: 24,
    pill: 999,
  },
  shadow: {
    soft: {
      shadowColor: "#6D28D9",
      shadowOpacity: 0.12,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 4,
    },
    strong: {
      shadowColor: "#6D28D9",
      shadowOpacity: 0.22,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 12 },
      elevation: 10,
    },
  },
  motion: {
    fast: 180,
    medium: 280,
    slow: 420,
  },
  layout: {
    bottomMenuSpace: 118,
  },
  brand: {
    name: "Dr Laundry",
    tagline: "Pickup, cleaning, and delivery that feels instant.",
    promise: "Doorstep laundry with zero hassle.",
  },
  glass: {
    backgroundColor: "rgba(255, 255, 255, 0.70)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.5)",
    shadowColor: "#6D28D9",
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  glassDark: {
    backgroundColor: "rgba(26, 16, 60, 0.70)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    shadowColor: "#000000",
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
};
